Parameters:
  MyVpcId:
    Description: We create security group for this vpc
    Type: AWS::EC2::VPC::Id
  MyApplication:  
    Description: Name of Machine
    Type: String
Resources:  
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: !Sub This used to create ssh in ${MyApplication} 
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp 
          ToPort: 22 
          FromPort: 22 
        - CidrIp: 192.168.0.0/25
          IpProtocol: tcp 
          ToPort: 22 
          FromPort: 22
      VpcId: !Ref MyVpcId
Outputs:
  SSHGroupId:
    Value: !Ref SSHSecurityGroup
    Description: Exported SSHSecurityGroup
    Export:
      Name: SSHSecurity     